import numpy as np

DEBUG=False

TIMESTEPS=1000
MAX_FORCE=50 # Newton*meters
GRAVITY_FORCE=-9.8 # m/s^2

NUM_MOTOR_NEURONS=9
NUM_SENSOR_NEURONS=4
MOTOR_JOINT_RANGE=0.5

# evolutionary parameters
NUMBER_OF_GENERATIONS=150
POPULATION_SIZE=20
