import numpy as np

DEBUG=False

TIMESTEPS=500
MAX_FORCE=50 # Newton*meters
GRAVITY_FORCE=-9.8 # m/s^2

NUM_MOTOR_NEURONS=9
NUM_SENSOR_NEURONS=4
MOTOR_JOINT_RANGE=0.5
NUM_MOTOR_VAL_BUCKETS=20
DEFAULT_EMPOWERMENT_WINDOW_SIZE=10
DEFAULT_OBJECTIVE='tri_fitness'

# evolutionary parameters
NUMBER_OF_GENERATIONS=50
POPULATION_SIZE=15
